name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]  # or your default branch
    paths:
      - 'my-docs/**'    # only run when docs change
  workflow_dispatch:     # allow manual runs

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Docusaurus requires Node.js 18+

      - name: Install dependencies
        run: |
          cd my-docs
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build Docusaurus site
        run: |
          cd my-docs
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: my-docs/build  # ✅ FIX: should be "my-docs/build" (your current setup is correct)
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
